apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: app
      app.kubernetes.io/name: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/component: app
        app.kubernetes.io/name: backend
    spec:
      containers:
        - name: main
          # [기본형] image: ghcr.io/[]/[IMAGE_NAME]:[TAG]        
          image: ghcr.io/eungsookim/backend:1.0.0
          imagePullPolicy: Always
      imagePullSecrets:
        - name: ghcr-read-secret