kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: ghcr-read-secret
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJZbVZ5TURFNloyaHdYek5qTlV0MFUxZElUMjlDZVZGdmRXUlRiVVJOY1RadGRWVnNhRXAxZURKdVJVNXhVQT09In19fQ==